server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newtable?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update